### ISSUE TITLE
「re」の追加

### ISSUE THREAD

**Issue by riku22** [actlaboratory/HISS-dictionary#22]
`re,リ,4`

を辞書に追加したいと考えています。
`recheck` とか、 `retried` とかが読めるようになるかと思います。
`un` が追加されているので、大丈夫かと思うのですが、問題が大きいでしょうか。
もし追加してもよさそうであれば、プルリクエストを作成したいと思います。

**Comment by yncat** [comment]
これ、メールが全部 リ: になってしまうので入れない方針にしてたんですが、それよりも、re+xxxの複合語が読めないほうが困りそうという話もあります。1回やってみますか。気に入らんかったら消せばいいので。PRお願いしますー

**Comment by riku22** [comment]
PR 出しました。
よろしくお願いします。
